language: php

php:
  - 5.2
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - pyrus set auto_discover 1
  - pyrus install --force phpunit/DbUnit
  - phpenv rehash

script:
  - phpunit --configuration tests/phpunit.xml
