language: php

php:
  - 5.2
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - phpenv rehash

script:
  - phpunit --configuration tests/phpunit.xml

notifications:
  email:
    recipients:
      - dcz@phpbb-seo.com
    on_success: never
    on_failure: always
